---
# This section commented out until packages have real repos
# Until then, curl bash install is really the only way

# OS-specific install routines
#- include: install-RedHat.yml
#  when: ansible_os_family == 'RedHat'

#- include: install-Debian.yml
#  when: ansible_os_family == 'Debian'

- name: Check if rexray installed
  stat:
    path: /usr/bin/rexray
  register: rexray_installed

- include: curlinstall.yml
  when: rexray_installed.stat.exists == False

- include: config.yml

- name: Ensure rexray is running
  service:
    name: rexray
    state: started
  when: rexray_service

- include: docker.yml
  when: rexray_docker is defined
